update

diff --git a/programs/setup/setup.in b/programs/setup/setup.in
--- a/programs/setup/setup.in
+++ b/programs/setup/setup.in
@@ -2,30 +2,23 @@
 # IPsec startup and shutdown command
 # Copyright (C) 1998, 1999, 2001  Henry Spencer.
 # Copyright (C) 2012 Paul Wouters <paul@libreswan.org>
-# Copyright (C) 2013 Tuomo Soini <tis@foobar.fi>
+# Copyright (C) 2013-2018 Tuomo Soini <tis@foobar.fi>
 # Copyright (C) 2016 Kim B. Heino <b@bbbs.net>
 #
 # This program is free software; you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published by the
 # Free Software Foundation; either version 2 of the License, or (at your
-# option) any later version.  See <http://www.fsf.org/copyleft/gpl.txt>.
+# option) any later version.  See <https://www.gnu.org/licenses/gpl2.txt>.
 #
 # This program is distributed in the hope that it will be useful, but
 # WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 # or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 # for more details.
 #
-# This is the version for use on Linux, see _realsetup.bsd for OSX/BSD
-
-IPSEC_CONF="${IPSEC_CONF:-@FINALCONFFILE@}"
-
+# This is the version for use on Linux.
 
 # Misc. paths (some of this should perhaps be overrideable from ipsec.conf).
-rundir=@FINALVARDIR@/run/pluto
-plutopid=${rundir}/pluto.pid
-plutoctl=${rundir}/pluto.ctl
-ipsecversion=/proc/net/ipsec_version
-kamepfkey=/proc/net/pfkey
+rundir=@IPSEC_RUNDIR@
 
 #pluto searches the current directory, so this is required for making it selinux compliant
 cd /
@@ -35,15 +28,12 @@ LIBRESWAN_RESOLV_CONF=${rundir}/libreswan-resolv-conf-backup
 ORIG_RESOLV_CONF=@FINALSYSCONFDIR@/resolv.conf
 
 
-if test `ip addr list|grep -c cipsec` -ne 0
-then
-	echo "Cisco IPSec client is already loaded, aborting! (cipsec# device found)"
-	exit 1
+if [ $(ip addr list|grep -c cipsec) -ne 0 ]; then
+    echo "Cisco IPsec client is already loaded, aborting! (cipsec# device found)"
+    exit 1
 fi
 
-# which kernel are we using?
-IPSECprotostack=`ipsec addconn --config $IPSEC_CONF --liststack`
-
+initsystem=unknown
 if [ -d /run/systemd/system ]; then
     initsystem=systemd
 elif [ -f /sbin/start ]; then
@@ -56,8 +46,6 @@ elif [ -f /sbin/rc-service ]; then
     initsystem=openrc
 elif [ -x /etc/init.d/ipsec ]; then
     initsystem=sysv
-else
-    initsystem=unknown
 fi
 
 case "$1" in
@@ -157,20 +145,11 @@ case "$1" in
 	exit 0
 	;;
     restart|--restart)
-	# assumes preparations for running have already been done, as service should be running now
+	# assumes preparations for running have already been done,
+	# as service should be running now
 	if [ ${initsystem} = systemd ]; then
-	    systemctl status ipsec.service > /dev/null
-	    RETVAL=$?
-	    if [ $RETVAL -ne 0 ]; then
-		echo "systemd: ipsec service is not running"
-		exit 1
-	    else
-		# do not use 'restart' because systemd is overly "smart"
-		# and will refuse the restart when stopped.
-		echo "Redirecting to: systemctl stop+start ipsec.service"
-		systemctl stop ipsec.service
-		exec systemctl start ipsec.service
-	    fi
+	    echo "Redirecting to: systemctl restart ipsec.service"
+	    exec systemctl restart ipsec.service
 	elif [ ${initsystem} = rhsysv ]; then
 	    echo "Redirecting to: service ipsec restart"
 	    exec service ipsec restart
