Update

diff --git a/programs/newhostkey/newhostkey.in b/programs/newhostkey/newhostkey.in
--- a/programs/newhostkey/newhostkey.in
+++ b/programs/newhostkey/newhostkey.in
@@ -4,13 +4,13 @@
 #
 # Copyright (C) 2001, 2002  Henry Spencer.
 # Copyright (C) 2014 Paul Wouters <pwouters@redhat.com>
-# Copyright (C) 2014 Tuomo Soini <tis@foobar.fi>
+# Copyright (C) 2014, 2016 Tuomo Soini <tis@foobar.fi>
 # Copyright (C) 2016, Andrew Cagney <cagney@gnu.org>
 #
 # This program is free software; you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published by the
 # Free Software Foundation; either version 2 of the License, or (at your
-# option) any later version.  See <http://www.fsf.org/copyleft/gpl.txt>.
+# option) any later version.  See <https://www.gnu.org/licenses/gpl2.txt>.
 #
 # This program is distributed in the hope that it will be useful, but
 # WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
@@ -20,14 +20,14 @@
 
 me="ipsec newhostkey"
 usage="Usage: $me [--output filename] [--seeddev device] [--bits n] \\
-    [--quiet] [--hostname host] [--configdir nssdbdir] [--password password] "
+    [--quiet] [--hostname host] [--nssdir @IPSEC_NSSDIR@] [--password password] "
 
 bits=
 verbose=
 host=
 seeddev="--seeddev /dev/random"
-output=""
-configdir="@FINALNSSDIR@"
+output=
+nssdir="@IPSEC_NSSDIR@"
 password=
 for dummy; do
     case "$1" in
@@ -50,11 +50,11 @@ for dummy; do
 	    verbose="--verbose"
 	    ;;
 	--version)
-	    echo "$me $IPSEC_VERSION"
+	    echo "${me} $IPSEC_VERSION"
 	    exit 0
 	    ;;
 	--random)
-	    echo "$me warning: --random is obsoleted, using --seeddev"
+	    echo "${me} warning: --random is obsoleted, using --seeddev" >&2
 	    seeddev="--seeddev ${2}"
 	    shift
 	    ;;
@@ -63,7 +63,12 @@ for dummy; do
 	    shift
 	    ;;
 	--configdir)
-	    configdir="${2}"
+	    echo "${me} warning: --configdir is obsoleted, use --nssdir" >&2
+	    nssdir="${2}"
+	    shift
+	    ;;
+	--nssdir)
+	    nssdir="${2}"
 	    shift
 	    ;;
 	--password)
@@ -79,7 +84,7 @@ for dummy; do
 	    break
 	    ;;
 	-*)
-	    echo "$me: unknown option \`$1'" >&2
+	    echo "${me}: unknown option \`$1'" >&2
 	    exit 2
 	    ;;
 	*)
@@ -98,20 +103,20 @@ if [ -n "${output}" -a -s "${output}" ]; then
     printf "%s: WARNING: file \"%s\" exists, appending to it\n" "${0}" "${output}" >&2
 fi
 
-if [ ! -d ${configdir} ]; then
-    echo "No such directory: ${configdir}"
+if [ ! -d ${nssdir} ]; then
+    echo "No such directory: ${nssdir}"
     exit 255
 fi
 
-certutil -L -d "sql:$configdir" >/dev/null 2>/dev/null
+certutil -L -d "sql:${nssdir}" >/dev/null 2>/dev/null
 RETVAL=$?
 if [ ${RETVAL} -eq 255 ]; then
-    echo "NSS database in $configdir not initialized."
-    echo "    Please run 'ipsec initnss --configdir $configdir'"
+    echo "NSS database in ${nssdir} not initialized."
+    echo "    Please run 'ipsec initnss --nssdir ${nssdir}'"
     exit 255
 fi
 
-key=$(ipsec rsasigkey ${verbose} ${seeddev} --configdir ${configdir} ${password} ${host} ${bits})
+key=$(ipsec rsasigkey ${verbose} ${seeddev} --nssdir ${nssdir} ${password} ${host} ${bits})
 RETVAL=$?
 if [ ${RETVAL} -ne 0 ]; then
     exit ${RETVAL}
@@ -130,7 +135,15 @@ out()
 
 if [ -n "${output}" ]; then
     umask 077
-    TEMPFILE=$(/bin/mktemp ${output}.XXXXXXX)
-    out > ${TEMPFILE}
+    TEMPFILE=$(mktemp ${output}.XXXXXXX)
+    RETVAL=$?
+    if [ ${RETVAL} -gt 0 ]; then
+	echo "${me}: error creating temporary file, aborting" >&2
+	exit ${RETVAL}
+    fi
+    if [ -f ${output} ]; then
+       cat ${output} >> ${TEMPFILE}
+    fi
+    out >> ${TEMPFILE}
     mv ${TEMPFILE} ${output}
 fi
